/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AiRouteImport } from './routes/ai'
import { Route as CampaignsRouteImport } from './routes/campaigns'
import { Route as CoachAymanRouteImport } from './routes/coach-ayman'
import { Route as ContactRouteImport } from './routes/contact'
